# This is an example of a custom composite gh action
name: 'Get & Cache Dependencies'
description: 'Get the dependencies via npm and cache them for future builds'
inputs:
  caching:
    description: 'Whether to use caching or not'
    required: false
    default: 'true'
runs:
  # composite is a keywork
  using: 'composite'
  steps:
    - name: Cache dependencies
      if: inputs.caching == 'true'
      id: cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true' || inputs.caching == 'false'
      run: npm ci
      shell: bash